// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoihfJ2vpujY34QE7tVAgif-vTuZNoXlc',
    appId: '1:548090626562:web:0767d79dcd5d4673169d1b',
    messagingSenderId: '548090626562',
    projectId: 'flutter-crashlytics-faaf4',
    authDomain: 'flutter-crashlytics-faaf4.firebaseapp.com',
    storageBucket: 'flutter-crashlytics-faaf4.appspot.com',
    measurementId: 'G-BTR3DBNW22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnV1_ZNWCapCsTv8d_qSNXiYqVrchYzwo',
    appId: '1:548090626562:android:2230b25f8f65a118169d1b',
    messagingSenderId: '548090626562',
    projectId: 'flutter-crashlytics-faaf4',
    storageBucket: 'flutter-crashlytics-faaf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqv0l0YQ5RHOuh4nnC8nUZtTanl0-lVts',
    appId: '1:548090626562:ios:fd53c5fbc5d08fa9169d1b',
    messagingSenderId: '548090626562',
    projectId: 'flutter-crashlytics-faaf4',
    storageBucket: 'flutter-crashlytics-faaf4.appspot.com',
    androidClientId: '548090626562-u7vsfdpd1m61kn1t2purjijnb9pi1erg.apps.googleusercontent.com',
    iosClientId: '548090626562-lq9pl3vddn6rb6vp2o7rt02l91kftmr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrashlyticsApp',
  );
}
